<a href="https://colab.research.google.com/github/hihowareyou2008/ML-Projects/blob/main/CreditCardFraudDetection_(With_Sampling).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [6]:
creditcard_data = pd.read_csv("/content/creditcard.csv")

In [7]:
creditcard_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [8]:
creditcard_data.shape

(41683, 31)

In [9]:
creditcard_data.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,41683.000000,41683.000000,41683.000000,41682.000000,41682.000000,41682.000000,41682.000000,41682.000000,41682.000000,41682.000000,...,41682.000000,41682.000000,41682.000000,41682.000000,41682.000000,41682.000000,41682.000000,41682.000000,41682.000000,41682.000000
mean,26208.345609,-0.222499,0.035454,0.711902,0.186781,-0.234719,0.099510,-0.112246,0.044579,0.193708,...,-0.028417,-0.111341,-0.040301,0.007295,0.136259,0.023199,0.008003,0.004864,89.104007,0.002591
std,12721.514541,1.855101,1.599923,1.490121,1.399707,1.387375,1.309662,1.238350,1.209428,1.220092,...,0.744449,0.638250,0.565217,0.593050,0.436860,0.504139,0.387877,0.341927,237.163503,0.050837
min,0.000000,-56.407510,-72.715728,-31.103685,-5.172595,-42.147898,-26.160506,-26.548144,-41.484823,-7.175097,...,-20.262054,-8.593642,-26.751119,-2.836627,-7.495741,-1.438650,-8.567638,-9.617915,0.000000,0.000000
25%,16853.000000,-0.974000,-0.533197,0.229759,-0.719018,-0.842162,-0.638071,-0.598424,-0.151197,-0.568666,...,-0.235257,-0.533250,-0.179117,-0.324744,-0.127717,-0.329707,-0.063304,-0.006814,7.500000,0.000000
50%,31305.000000,-0.240189,0.093834,0.811276,0.185168,-0.272258,-0.156277,-0.073482,0.050183,0.071496,...,-0.074873,-0.085641,-0.051385,0.060759,0.175870,-0.064901,0.008653,0.021615,24.000000,0.000000
75%,36289.000000,1.159396,0.740067,1.443056,1.069459,0.293052,0.485883,0.432308,0.318625,0.906980,...,0.102520,0.300633,0.077243,0.400073,0.421184,0.304378,0.085015,0.076216,80.000000,0.000000
max,40784.000000,1.960497,16.713389,4.101716,16.491217,34.801666,22.529298,36.677268,20.007208,10.392889,...,22.614889,5.805795,17.297845,4.014444,5.525093,3.517346,11.135740,33.847808,7879.420000,1.000000

In [10]:
creditcard_data.isnull().sum()

Time      0
V1        0
V2        0
V3        1
V4        1
V5        1
V6        1
V7        1
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [11]:
creditcard_data['Class'].value_counts()

Class
0.0    41574
1.0      108
Name: count, dtype: int64

In [12]:
# Seperating the data for analysis
legit = creditcard_data[creditcard_data.Class == 0]
fraud = creditcard_data[creditcard_data.Class == 1]

In [13]:
print(legit.shape)
print(fraud.shape)

(41574, 31)
(108, 31)

In [14]:
legit.Amount.describe()

count    41574.000000
mean        89.092554
std        237.129967
min          0.000000
25%          7.550000
50%         24.000000
75%         80.000000
max       7879.420000
Name: Amount, dtype: float64

In [15]:
fraud.Amount.describe()

count     108.000000
mean       93.512593
std       250.863273
min         0.000000
25%         1.000000
50%         2.320000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [16]:
# Compare the values for both transactions
creditcard_data.groupby("Class").mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,26220.447082,-0.203702,0.021029,0.74135,0.172070,-0.222039,0.105713,-0.093360,0.035106,0.201757,...,0.045420,-0.030057,-0.110755,-0.039591,0.007931,0.135806,0.022783,0.005968,0.004583,89.092554
1.0,21414.990741,-7.454643,5.595067,-10.62406,5.849772,-5.115950,-2.288288,-7.382457,3.691487,-2.904887,...,0.630658,0.602725,-0.336878,-0.313708,-0.237598,0.310378,0.183470,0.791559,0.112874,93.512593

Under-Sampling

Build a sample dtatset containing simillar distributions of normal transactions and fraud transactions

Numer of fraud transactions --> 492

In [17]:
legit_sample = legit.sample(n=492)

In [18]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [19]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
11018,18991,1.284475,-0.528597,-0.551952,-1.692217,1.390419,3.487251,-1.223489,0.875786,2.954982,...,-0.208136,-0.272552,-0.070785,0.957666,0.636471,-0.711079,0.068018,0.024173,11.85,0.0
31129,36225,-0.469985,-0.039085,1.008465,-0.474125,-1.420172,0.129689,-0.198793,0.431130,-1.281089,...,0.481915,1.190264,0.362401,0.132442,-0.776724,-0.134858,0.089507,0.148785,145.20,0.0
34070,37499,1.037654,-0.311294,1.626483,1.827284,-1.348433,0.083178,-0.752943,0.179903,1.371418,...,0.088589,0.656372,-0.159308,0.772353,0.641410,-0.146766,0.087586,0.041597,37.88,0.0
16538,27911,1.521184,-1.192308,0.641468,-1.382963,-1.803349,-0.641546,-1.358176,-0.036497,-1.349570,...,-0.100412,0.055451,-0.028167,-0.022820,0.338319,-0.076052,0.041788,0.020591,13.00,0.0
30980,36162,-0.727848,0.373772,1.190583,-0.137195,2.045394,4.745193,0.098815,0.958508,0.581044,...,-0.484753,-1.028601,-0.275524,0.993606,0.533702,-0.530715,-0.163672,-0.162889,56.07,0.0

In [20]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
39183,39729,-0.964567,-1.643541,-0.187727,1.158253,-2.458336,0.852222,2.785163,-0.303609,0.940006,...,0.447180,0.536204,1.634061,0.203839,0.218749,-0.221886,-0.308555,-0.164500,776.83,1.0
40085,40086,1.083693,1.179501,-1.346150,1.998824,0.818034,-0.771419,0.230307,0.093683,-0.167594,...,-0.312000,-0.639700,-0.120249,-0.180218,0.609283,-0.339524,0.096701,0.114972,1.00,1.0
40525,40276,1.159373,2.844795,-4.050680,4.777701,2.948980,-2.010361,1.744086,-0.410287,-2.450198,...,-0.176541,-0.433470,-0.529323,-0.597020,1.335954,0.547092,0.009979,0.160769,1.00,1.0
41395,40662,-4.446847,-0.014793,-5.126307,6.945130,5.269255,-4.297177,-2.591242,0.342671,-3.880663,...,0.247913,-0.049586,-0.226017,-0.401236,0.856124,0.661272,0.492560,0.971834,1.00,1.0
41569,40742,-2.377533,0.520539,-8.094139,8.005351,2.640750,-3.381586,-1.934372,0.562322,-3.104027,...,0.148284,0.721100,2.661291,-0.508620,-0.401657,0.587611,0.500326,0.551760,1.00,1.0

In [21]:
new_dataset['Class'].value_counts()

Class
0.0    492
1.0    108
Name: count, dtype: int64

In [22]:
new_dataset.groupby("Class").mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,26644.792683,-0.255997,-0.087752,0.61426,0.117568,-0.07380,0.142425,-0.106092,0.151105,0.160307,...,0.075830,-0.026601,-0.141853,0.003906,0.068793,0.142943,0.008518,0.004341,0.015822,97.038537
1.0,21414.990741,-7.454643,5.595067,-10.62406,5.849772,-5.11595,-2.288288,-7.382457,3.691487,-2.904887,...,0.630658,0.602725,-0.336878,-0.313708,-0.237598,0.310378,0.183470,0.791559,0.112874,93.512593

In [23]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [24]:
print(X)
print(Y)

        Time        V1        V2        V3        V4        V5        V6  \
11018  18991  1.284475 -0.528597 -0.551952 -1.692217  1.390419  3.487251
31129  36225 -0.469985 -0.039085  1.008465 -0.474125 -1.420172  0.129689
34070  37499  1.037654 -0.311294  1.626483  1.827284 -1.348433  0.083178
16538  27911  1.521184 -1.192308  0.641468 -1.382963 -1.803349 -0.641546
30980  36162 -0.727848  0.373772  1.190583 -0.137195  2.045394  4.745193
...      ...       ...       ...       ...       ...       ...       ...
39183  39729 -0.964567 -1.643541 -0.187727  1.158253 -2.458336  0.852222
40085  40086  1.083693  1.179501 -1.346150  1.998824  0.818034 -0.771419
40525  40276  1.159373  2.844795 -4.050680  4.777701  2.948980 -2.010361
41395  40662 -4.446847 -0.014793 -5.126307  6.945130  5.269255 -4.297177
41569  40742 -2.377533  0.520539 -8.094139  8.005351  2.640750 -3.381586

             V7        V8        V9  ...       V20       V21       V22  \
11018 -1.223489  0.875786  2.954982  ... -0.015415 -0.208136 -0.272552
31129 -0.198793  0.431130 -1.281089  ...  0.403063  0.481915  1.190264
34070 -0.752943  0.179903  1.371418  ... -0.106025  0.088589  0.656372
16538 -1.358176 -0.036497 -1.349570  ... -0.400453 -0.100412  0.055451
30980  0.098815  0.958508  0.581044  ...  0.094282 -0.484753 -1.028601
...         ...       ...       ...  ...       ...       ...       ...
39183  2.785163 -0.303609  0.940006  ...  1.784449  0.447180  0.536204
40085  0.230307  0.093683 -0.167594  ... -0.060159 -0.312000 -0.639700
40525  1.744086 -0.410287 -2.450198  ... -0.059264 -0.176541 -0.433470
41395 -2.591242  0.342671 -3.880663  ... -0.108006  0.247913 -0.049586
41569 -1.934372  0.562322 -3.104027  ... -0.634747  0.148284  0.721100

            V23       V24       V25       V26       V27       V28  Amount
11018 -0.070785  0.957666  0.636471 -0.711079  0.068018  0.024173   11.85
31129  0.362401  0.132442 -0.776724 -0.134858  0.089507  0.148785  145.20
34070 -0.159308  0.772353  0.641410 -0.146766  0.087586  0.041597   37.88
16538 -0.028167 -0.022820  0.338319 -0.076052  0.041788  0.020591   13.00
30980 -0.275524  0.993606  0.533702 -0.530715 -0.163672 -0.162889   56.07
...         ...       ...       ...       ...       ...       ...     ...
39183  1.634061  0.203839  0.218749 -0.221886 -0.308555 -0.164500  776.83
40085 -0.120249 -0.180218  0.609283 -0.339524  0.096701  0.114972    1.00
40525 -0.529323 -0.597020  1.335954  0.547092  0.009979  0.160769    1.00
41395 -0.226017 -0.401236  0.856124  0.661272  0.492560  0.971834    1.00
41569  2.661291 -0.508620 -0.401657  0.587611  0.500326  0.551760    1.00

[600 rows x 30 columns]
11018    0.0
31129    0.0
34070    0.0
16538    0.0
30980    0.0
        ...
39183    1.0
40085    1.0
40525    1.0
41395    1.0
41569    1.0
Name: Class, Length: 600, dtype: float64

In [25]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

In [26]:
print(X_train)
print(Y_train)

        Time        V1        V2         V3         V4        V5        V6  \
40387  40217 -1.176072  1.182193  -0.234710  -1.192087  2.259494  3.628699
6089    6947 -0.730817  0.050766   1.748493  -1.573485  0.267686 -0.802624
2083    1607  1.573518 -1.238549  -0.920907  -2.511648  0.839558  3.338818
26993  34339 -1.432023  1.292896   1.885914   0.674371 -0.217006 -0.488614
38875  39593  1.368329 -0.648905   0.033468  -0.736155 -0.816690 -0.575449
...      ...       ...       ...        ...        ...       ...       ...
10568  17520 -5.268053  9.067613 -15.960728  10.296603 -4.708241 -3.395375
27749  34687 -0.860827  3.131790  -5.052968   5.420941 -2.494141 -1.811287
623      472 -3.043541 -3.157307   1.088463   2.288644  1.359805 -1.064823
9252   13323 -5.454362  8.287421 -12.752811   8.594342 -3.106002 -3.179949
33485  37252 -0.128908  0.468248   1.390037  -0.140783  0.175315 -0.648259

              V7        V8        V9  ...       V20       V21       V22  \
40387   0.097932  1.018184  0.389587  ...  0.573752 -0.338314 -0.651210
6089    0.672366 -0.180118  2.095819  ... -0.219757 -0.459721 -1.118489
2083   -1.656426  0.809151 -1.875791  ... -0.208437 -0.310203 -0.649184
26993   0.697935 -0.172160  0.328637  ...  0.583006  0.001158  0.587428
38875  -0.456373 -0.153602 -0.695908  ... -0.399907 -0.524766 -1.169819
...          ...       ...       ...  ...       ...       ...       ...
10568 -11.161057  5.499963 -5.667376  ...  1.455878  2.004110  0.191058
27749  -5.479117  1.189472 -3.908206  ...  1.085760  1.192694  0.090356
623     0.325574 -0.067794 -0.270953  ...  2.102339  0.661696  0.435477
9252   -9.252794  4.245062 -6.329801  ...  1.305862  1.846165 -0.267172
33485   0.903550 -0.343888  0.301043  ... -0.011704  0.058409  0.564794

            V23       V24       V25       V26       V27       V28  Amount
40387 -0.166658  1.016312  0.293740  0.269194  0.644124  0.353860   13.59
6089  -0.016018 -0.201205 -0.302263  0.853918 -0.265714 -0.140116   40.00
2083   0.066047  0.968291  0.415819 -0.265771  0.045386  0.019063    7.00
26993 -0.394565  0.401964  0.641309 -0.105443  0.481983  0.203135   41.51
38875  0.009713 -0.463772  0.171107  0.954163 -0.068062  0.008666   50.00
...         ...       ...       ...       ...       ...       ...     ...
10568  0.622928 -1.209264 -0.374799  0.648798  1.584697  0.720056    1.00
27749 -0.341881 -0.215924  1.053032  0.271139  1.373300  0.691195   19.02
623    1.375966 -0.293803  0.279798 -0.145362 -0.252773  0.035764  529.00
9252  -0.310804 -1.201685  1.352176  0.608425  1.574715  0.808725    1.00
33485  0.042930  0.468724 -0.924087  0.020595  0.036488  0.009390   28.75

[480 rows x 30 columns]
40387    0.0
6089     0.0
2083     0.0
26993    0.0
38875    0.0
        ...
10568    1.0
27749    1.0
623      1.0
9252     1.0
33485    0.0
Name: Class, Length: 480, dtype: float64

In [27]:
model = LogisticRegression()

In [28]:
model.fit(X_train, Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [29]:
X_train_pred = model.predict(X_train)
X_test_pred = model.predict(X_test)
training_data_accuracy = accuracy_score(X_train_pred, Y_train)
testing_data_accuracy = accuracy_score(X_test_pred, Y_test)

In [30]:
print(training_data_accuracy)
print(testing_data_accuracy)

0.975
0.9666666666666667