<a href="https://colab.research.google.com/github/hihowareyou2008/ML-Projects/blob/main/Titanic_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
titanic_data = pd.read_csv("/content/train.csv")

In [3]:
titanic_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
titanic_data.shape

(891, 12)

In [5]:
titanic_data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [6]:
titanic_data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
titanic_data['Age'].fillna(titanic_data['Age'].mean(), inplace=True)

/tmp/ipykernel_7791/3516126430.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic_data['Age'].fillna(titanic_data['Age'].mean(), inplace=True)

In [8]:
titanic_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [9]:
label_encode = LabelEncoder()

In [10]:
label_1 = label_encode.fit_transform(titanic_data.Name)
label_2 = label_encode.fit_transform(titanic_data.Sex)
label_3 = label_encode.fit_transform(titanic_data.Ticket)
label_4 = label_encode.fit_transform(titanic_data.Cabin)
label_5 = label_encode.fit_transform(titanic_data.Embarked)

In [11]:
titanic_data['Name'] = label_1
titanic_data['Sex'] = label_2
titanic_data['Ticket'] = label_3
titanic_data['Cabin'] = label_4
titanic_data['Embarked'] = label_5

In [12]:
titanic_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,108,1,22.0,1,0,523,7.2500,147,2
1,2,1,1,190,0,38.0,1,0,596,71.2833,81,0
2,3,1,3,353,0,26.0,0,0,669,7.9250,147,2
3,4,1,1,272,0,35.0,1,0,49,53.1000,55,2
4,5,0,3,15,1,35.0,0,0,472,8.0500,147,2

In [13]:
titanic_data['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [14]:
X = titanic_data.drop(columns='Survived', axis=1)
Y = titanic_data['Survived']

In [15]:
print(X)
print(Y)

     PassengerId  Pclass  Name  Sex        Age  SibSp  Parch  Ticket     Fare  \
0              1       3   108    1  22.000000      1      0     523   7.2500
1              2       1   190    0  38.000000      1      0     596  71.2833
2              3       3   353    0  26.000000      0      0     669   7.9250
3              4       1   272    0  35.000000      1      0      49  53.1000
4              5       3    15    1  35.000000      0      0     472   8.0500
..           ...     ...   ...  ...        ...    ...    ...     ...      ...
886          887       2   548    1  27.000000      0      0     101  13.0000
887          888       1   303    0  19.000000      0      0      14  30.0000
888          889       3   413    0  29.699118      1      2     675  23.4500
889          890       1    81    1  26.000000      0      0       8  30.0000
890          891       3   220    1  32.000000      0      0     466   7.7500

     Cabin  Embarked
0      147         2
1       81         0
2      147         2
3       55         2
4      147         2
..     ...       ...
886    147         2
887     30         2
888    147         2
889     60         0
890    147         1

[891 rows x 11 columns]
0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [16]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1, random_state=1)

In [17]:
print(X.shape, X_train.shape, X_test.shape)

(891, 11) (801, 11) (90, 11)

In [18]:
print(X_train)
print(Y_train)

     PassengerId  Pclass  Name  Sex        Age  SibSp  Parch  Ticket     Fare  \
662          663       1   171    1  47.000000      0      0     496  25.5875
584          585       3   640    1  29.699118      0      0     291   8.7125
703          704       3   275    1  25.000000      0      0     449   7.7417
47            48       3   604    0  29.699118      0      0      76   7.7500
868          869       3   890    1  29.699118      0      0     309   9.5000
..           ...     ...   ...  ...        ...    ...    ...     ...      ...
715          716       3   773    1  19.000000      0      0     348   7.6500
767          768       3   506    0  30.500000      0      0     436   7.7500
72            73       2   376    1  21.000000      0      0     621  73.5000
235          236       3   329    0  29.699118      0      0     677   7.5500
37            38       3   134    1  21.000000      0      0     514   8.0500

     Cabin  Embarked
662    132         2
584    147         0
703    147         1
47     147         1
868    147         2
..     ...       ...
715    140         2
767    147         1
72     147         2
235    147         2
37     147         2

[801 rows x 11 columns]
662    0
584    0
703    0
47     1
868    0
      ..
715    0
767    0
72     0
235    0
37     0
Name: Survived, Length: 801, dtype: int64

In [19]:
model = LogisticRegression()

In [20]:
model.fit(X_train, Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [21]:
X_train_pred = model.predict(X_train)
X_test_pred = model.predict(X_test)
training_data_accuracy = accuracy_score(X_train_pred, Y_train)
testing_data_accuracy = accuracy_score(X_test_pred, Y_test)

In [22]:
print(training_data_accuracy)
print(testing_data_accuracy)

0.7990012484394506
0.7333333333333333